stages:
  - test
  - build

test:syntax:
  stage: test
  image: python:3.9-slim
  script:
    - echo "Verificando sintaxe do código Python..."
    - python -m py_compile app.py
    - pip install -r requirements.txt
    - python -c "import app; print('Sintaxe válida!')"

build:docker:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "Construindo imagem Docker..."
    - docker build -t app-votacao:test .
    - echo "Imagem construída com sucesso!"
    - docker images